"""Setup module for TechMiner2+"""

from setuptools import find_packages, setup  # type: ignore[import]

setup(
    # cmdclass={"build_py": BuildPyCommand},
    name="techminer2",
    version="2024.7.22",
    author="Juan D. Velasquez",
    author_email="jdvelasq@unal.edu.co",
    license="MIT",
    url="http://github.com/jdvelasq/techminer2",
    description="Tech Mining Analysis of Bibliography",
    long_description="Tech Mining Analysis of Bibliography",
    keywords="bibliography",
    platforms="any",
    provides=["techminer2"],
    install_requires=[
        "cdlib",
        "colorama",
        "contractions",
        "duckdb",
        "fuzzywuzzy",
        "graphviz",
        "igraph",
        "kaleido",
        "keybert",
        "langdetect",
        "leidenalg",
        "networkx",
        "nltk",
        "pandarallel",
        "pandas",
        "plotly",
        "pyahocorasick",
        "pyparsing<3.1",
        "pyspellchecker",
        "python-Levenshtein",
        "PyYAML",
        "pyzotero",
        "scikit-learn",
        "spacy",
        "sumy",
        "tabulate",
        "textblob",
        "textdistance",
        "typing_extensions",
        "urllib3",
        "wordcloud",
    ],
    packages=find_packages(),
    package_dir={"techminer2": "techminer2"},
    include_package_data=True,
    classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: MIT License",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Education",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
    ],
)
