"""Setup module for tm2p+"""

from setuptools import find_packages, setup  # type: ignore[import]

setup(
    # cmdclass={"build_py": BuildPyCommand},
    name="tm2p",
    version="2024.7.22",
    author="Juan D. Velasquez",
    author_email="jdvelasq@unal.edu.co",
    license="MIT",
    url="http://github.com/jdvelasq/tm2p",
    description="Tech Mining Analysis of Bibliography",
    long_description="Tech Mining Analysis of Bibliography",
    keywords="bibliography",
    platforms="any",
    provides=["tm2p"],
    install_requires=[
        "cdlib==0.4.0",
        "colorama==0.4.6",
        "contractions==0.1.73",
        "duckdb==1.4.4",
        "fuzzywuzzy==0.18.0",
        "graphviz==0.21",
        "igraph==1.0.0",
        "kaleido==1.2.0",
        "keybert==0.9.0",
        "langdetect==1.0.9",
        "leidenalg==0.11.0",
        "networkx==3.2.1",
        "nltk==3.9.2",
        "pandarallel==1.6.5",
        "pandas==2.3.3",
        "plotly==6.5.2",
        "pyahocorasick==2.2.0",
        "pyparsing==3.0.9",
        "pyspellchecker==0.8.4",
        "python-Levenshtein==0.27.1",
        "PyYAML==6.0.3",
        "pyzotero==1.10.0",
        "scikit-learn==1.6.1",
        "spacy==3.8.11",
        "sumy==0.12.0",
        "tabulate==0.9.0",
        "textblob==0.19.0",
        "textdistance==4.6.3",
        "typing_extensions==4.15.0",
        "urllib3==1.26.20",
        "wordcloud==1.9.6",
    ],
    packages=find_packages(),
    package_dir={"tm2p": "tm2p"},
    include_package_data=True,
    classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: MIT License",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Education",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
    ],
)
