_COUNTRY_REPLACEMENTS = [
    ("Bosnia and Herz.", "Bosnia and Herzegovina"),
    ("Brasil", "Brazil"),
    ("Central African Rep.", "Central African Republic"),
    ("Congo, Democratic Republic of The", "Democratic Republic of The Congo"),
    ("Côte D'Ivoire", "Cote D'Ivoire"),
    ("Czech Republic", "Czechia"),
    ("Dem. Rep. Congo", "Democratic Republic of The Congo"),
    ("Dominican Rep.", "Dominican Republic"),
    ("England", "United Kingdom"),
    ("Eq. Guinea", "Equatorial Guinea"),
    ("Espana", "Spain"),
    ("Falkland Is.", "Falkland Islands"),
    ("Macao", "China"),
    ("Macau", "China"),
    ("México", "Mexico"),
    ("Moscow", "Russia"),
    ("N. Cyprus", "Cyprus"),
    ("P R China", "China"),
    ("Palestine, State Of", "Palestine"),
    ("Peoples R China", "China"),
    ("Perú", "Peru"),
    ("Republic of Ireland", "Ireland"),
    ("Republic of Korea", "South Korea"),
    ("Republic of Moldova", "Moldova"),
    ("Rusia", "Russia"),
    ("Russian Federation", "Russia"),
    ("Saint Helena, Ascension and Tristan Da Cunha", "Saint Helena"),
    ("Solomon Is.", "Solomon Islands"),
    ("St. Kitts and Nevis", "Saint Kitts and Nevis"),
    ("St. Lucia", "Saint Lucia"),
    ("St. Vincent and The Grenadines", "Saint Vincent and The Grenadines"),
    ("Syrian Arab Republic", "Syria"),
    ("the Netherlands", "Netherlands"),
    ("The Netherlands", "Netherlands"),
    ("The Philippines", "Philippines"),
    ("Trinidad & Tobago", "Trinidad and Tobago"),
    ("Türkiye", "Turkey"),
    ("U Arab Emirates", "United Arab Emirates"),
    ("U.S.A", "United States"),
    ("UK", "United Kingdom"),
    ("United States of America", "United States"),
    ("USA", "United States"),
    ("Viet Nam", "Vietnam"),
    ("Viet-Nam", "Vietnam"),
    ("W. Sahara", "Western Sahara"),
]
