from types import MappingProxyType

CHEMICAL_COMPOUNDS = MappingProxyType(
    {
        "ag": "silver",
        "ag/agcl": "silver silver chloride composite",
        "ag/c": "silver carbon composite",
        "ag/cu": "silver copper composite",
        "ag/tio": "silver titanium oxide composite",
        "ag/zno": "silver zinc oxide composite",
        "ag2s": "silver sulfide",
        "al": "aluminum",
        "al2o3": "aluminum oxide",
        "au nanoparticles": "gold nanoparticles",
        "au": "gold",
        "au/tio": "gold titanium oxide composite",
        "au/tio2": "gold titanium dioxide composite",
        "au/zno": "gold zinc oxide composite",
        "b/n": "boron nitride composite",
        "ba": "barium",
        "bc/go": "biochar graphene oxide composite",
        "bi2o3": "bismuth oxide",
        "bi2s3": "bismuth sulfide",
        "br/i": "bromine iodine composite",
        "c2h2": "acetylene",
        "c2h4": "ethylene",
        "c2h5oh": "ethanol",
        "c2h6": "ethane",
        "c2n": "carbon nitride",
        "c3n4-based": "carbon nitride based",
        "c3n4-ns": "carbon nitride ns",
        "c3n4-polypyrrole": "carbon nitride polypyrrole",
        "c3n4": "carbon nitride",
        "c6h12o6": "glucose",
        "c6h6": "benzene",
        "ca": "calcium",
        "ca(oh)2": "calcium hydroxide",
        "ca/mg": "calcium magnesium composite",
        "caco3": "calcium carbonate",
        "cds": "cadmium sulfide",
        "cds/mos": "cadmium sulfide molybdenum sulfide composite",
        "cds/nis": "cadmium sulfide nickel sulfide composite",
        "cds/sb": "cadmium sulfide antimony composite",
        "cds/tio": "cadmium sulfide titanium oxide composite",
        "cdse": "cadmium selenide",
        "cdse/cds": "cadmium selenide cadmium sulfide composite",
        "cdse/zns": "cadmium selenide zinc sulfide composite",
        "ch3cooh": "acetic acid",
        "ch3oh": "methanol",
        "ch4": "methane",
        "co/al": "cobalt aluminum composite",
        "co/c": "cobalt carbon composite",
        "co/fe": "cobalt iron composite",
        "co/mo": "cobalt molybdenum composite",
        "co/ni": "cobalt nickel composite",
        "co2": "carbon dioxide",
        "co2p": "cobalt phosphide",
        "co3o4": "cobalt oxide",
        "co9s8": "cobalt sulfide",
        "coo": "cobalt oxide",
        "cu": "copper",
        "cu/ag": "copper silver composite",
        "cu/al": "copper aluminum composite",
        "cu/c": "copper carbon composite",
        "cu/ca": "copper calcium composite",
        "cu/ceo": "copper cerium oxide composite",
        "cu/fe": "copper iron composite",
        "cu/in": "copper indium composite",
        "cu/ni": "copper nickel composite",
        "cu/tio": "copper titanium oxide composite",
        "cu/zn": "copper zinc composite",
        "cu/zno": "copper zinc oxide composite",
        "cu/zno/al": "copper zinc oxide aluminum composite",
        "cu/zro": "copper zirconium oxide composite",
        "cu2o": "copper oxide",
        "cu2s": "copper sulfide",
        "cu3p": "copper phosphide",
        "cuo": "copper oxide",
        "cuo/zno": "copper oxide zinc oxide composite",
        "ec/dmc": "ethylene carbonate dimethyl carbonate composite",
        "fe": "iron",
        "fe/c": "iron carbon composite",
        "fe/cao": "iron calcium oxide composite",
        "fe/co": "iron cobalt composite",
        "fe/mn": "iron manganese composite",
        "fe/ni": "iron nickel composite",
        "fe2o3": "iron oxide",
        "fe3c": "iron carbide",
        "fe3o4": "iron oxide",
        "fto/sno": "fluorine tin oxide tin oxide composite",
        "fto/tio": "fluorine tin oxide titanium oxide composite",
        "g-c3n4": "carbon nitride",
        "ga2o3": "gallium oxide",
        "go/fe": "graphene oxide iron composite",
        "graphitic carbon nitride": "carbon nitride",
        "h2": "hydrogen",
        "h2o2": "hydrogen peroxide",
        "h2s": "hydrogen sulfide",
        "h2so4": "sulfuric acid",
        "h3po4": "phosphoric acid",
        "hcl": "hydrochloric acid",
        "hcooh": "formic acid",
        "hg/hgo": "mercury mercury oxide composite",
        "hno3": "nitric acid",
        "i/br": "iodine bromine composite",
        "in2o3": "indium oxide",
        "in2s3": "indium sulfide",
        "in2se3": "indium selenide",
        "ingan/gan": "indium gallium nitride gallium nitride composite",
        "ir/c": "iridium carbon composite",
        "ir/moc": "iridium molybdenum carbide composite",
        "ito/pedot": "indium tin oxide pedot composite",
        "ito/sno": "indium tin oxide tin oxide composite",
        "ito/zno": "indium tin oxide zinc oxide composite",
        "k/al": "potassium aluminum composite",
        "koh": "potassium hydroxide",
        "lco": "lithium cobalt oxide",
        "lfp": "lithium iron phosphate",
        "lfp/c": "lithium iron phosphate carbon composite",
        "li": "lithium",
        "li/na": "lithium sodium composite",
        "li/na/k": "lithium sodium potassium composite",
        "li/ni": "lithium nickel composite",
        "li2o": "lithium oxide",
        "li2o2": "lithium peroxide",
        "li2s": "lithium sulfide",
        "licoo2": "lithium cobalt oxide",
        "lifepo4": "lithium iron phosphate",
        "limn2o4": "lithium manganese oxide",
        "mg/al": "magnesium aluminum composite",
        "mg/fe": "magnesium iron composite",
        "mgso4": "magnesium sulfate",
        "mn": "manganese",
        "mn3o4": "manganese oxide",
        "mno2": "manganese oxide",
        "mo2c": "molybdenum carbide",
        "moo3": "molybdenum oxide",
        "mos2": "molybdenum sulfide",
        "mos2/graphene": "molybdenum sulfide graphene composite",
        "n2": "nitrogen",
        "n2o": "nitrous oxide",
        "na": "sodium",
        "na/fe": "sodium iron composite",
        "na/k": "sodium potassium composite",
        "na3v2": "sodium vanadium composite",
        "nacl": "sodium chloride",
        "nahco3": "sodium bicarbonate",
        "naoh": "sodium hydroxide",
        "nb2o5": "niobium oxide",
        "nca": "nickel cobalt aluminum",
        "ncm": "nickel cobalt manganese",
        "nh3": "ammonia",
        "ni": "nickel",
        "ni(oh)2": "nickel hydroxide",
        "ni/bc": "nickel biochar composite",
        "ni/c": "nickel carbon composite",
        "ni/ceo": "nickel cerium oxide composite",
        "ni/co": "nickel cobalt composite",
        "ni/cu": "nickel copper composite",
        "ni/fe": "nickel iron composite",
        "ni/la": "nickel lanthanum composite",
        "ni/mg": "nickel magnesium composite",
        "ni/mgal": "nickel magnesium aluminum composite",
        "ni/mgo": "nickel magnesium oxide composite",
        "ni/sio": "nickel silicon oxide composite",
        "ni/tio": "nickel titanium oxide composite",
        "ni/ysz": "nickel yttria stabilized zirconia composite",
        "ni/zro": "nickel zirconium oxide composite",
        "ni2p": "nickel phosphide",
        "ni3n": "nickel nitride",
        "ni3s2": "nickel sulfide",
        "ni3se2": "nickel selenide",
        "nio": "nickel oxide",
        "nio/ni": "nickel oxide nickel composite",
        "nmc": "nickel manganese cobalt",
        "o2": "oxygen",
        "pb": "lead",
        "pd": "palladium",
        "pd/c": "palladium carbon composite",
        "pd/in": "palladium indium composite",
        "pd/tio": "palladium titanium oxide composite",
        "pd/zno": "palladium zinc oxide composite",
        "pe": "polyethylene",
        "pet": "polyethylene terephthalate",
        "pp": "polypropylene",
        "ps": "polystyrene",
        "pt": "platinum",
        "pt/al": "platinum aluminum composite",
        "pt/c": "platinum carbon composite",
        "pt/cnt": "platinum carbon nanotube composite",
        "pt/co": "platinum cobalt composite",
        "pt/ni": "platinum nickel composite",
        "pt/ti": "platinum titanium composite",
        "pt/tio": "platinum titanium oxide composite",
        "pt/tio2": "platinum titanium dioxide composite",
        "ptfe": "polytetrafluoroethylene",
        "ptru/c": "platinum ruthenium carbon composite",
        "pvc": "polyvinyl chloride",
        "rh/c": "rhodium carbon composite",
        "ru": "ruthenium",
        "ru/al": "ruthenium aluminum composite",
        "ru/c": "ruthenium carbon composite",
        "ru/ceo": "ruthenium cerium oxide composite",
        "ru/ni": "ruthenium nickel composite",
        "ru/ruo": "ruthenium ruthenium oxide composite",
        "ru/tio": "ruthenium titanium oxide composite",
        "s/b": "sulfur boron composite",
        "s/se": "sulfur selenium composite",
        "sb2s3": "antimony sulfide",
        "sb2se3": "antimony selenide",
        "si": "silicon",
        "si/al": "silicon aluminum composite",
        "si/c": "silicon carbon composite",
        "si/pedot": "silicon pedot composite",
        "sic/cno": "silicon carbide carbon nitride oxide composite",
        "sic/cnos": "silicon carbide carbon nitride oxide composite",
        "sno2": "tin oxide",
        "sno₂": "tin oxide",
        "ta3n5": "tantalum nitride",
        "ta₃n₅": "tantalum nitride",
        "ti": "titanium",
        "ti/pbo": "titanium lead oxide composite",
        "ti/ruo": "titanium ruthenium oxide composite",
        "ti/tio": "titanium titanium oxide composite",
        "ti3c2": "titanium carbide",
        "ti4o7": "titanium oxide",
        "tio2": "titanium dioxide",
        "v2o5": "vanadium oxide",
        "wo3": "tungsten oxide",
        "ws2": "tungsten sulfide",
        "zn": "zinc",
        "zn/co": "zinc cobalt composite",
        "zn/mno": "zinc manganese oxide composite",
        "zno": "zinc oxide",
        "zno/al": "zinc oxide aluminum composite",
        "zno/tio": "zinc oxide titanium oxide composite",
        "zr/ce": "zirconium cerium composite",
    }
)
