from types import MappingProxyType

COUNTRY_TO_REGION = MappingProxyType(
    {
        "Afghanistan": "Asia",
        "Albania": "Europe",
        "Algeria": "Africa",
        "American Samoa": "Oceania",
        "Andorra": "Europe",
        "Angola": "Africa",
        "Anguilla": "Americas",
        "Antarctica": "Antarctica",
        "Antigua and Barbuda": "Americas",
        "Argentina": "Americas",
        "Armenia": "Asia",
        "Aruba": "Americas",
        "Australia": "Oceania",
        "Austria": "Europe",
        "Azerbaijan": "Asia",
        "Bahamas": "Americas",
        "Bahrain": "Asia",
        "Bangladesh": "Asia",
        "Barbados": "Americas",
        "Belarus": "Europe",
        "Belgium": "Europe",
        "Belize": "Americas",
        "Benin": "Africa",
        "Bermuda": "Americas",
        "Bhutan": "Asia",
        "Bolivia": "Americas",
        "Bonaire": "Americas",
        "Bosnia and Herzegovina": "Europe",
        "Botswana": "Africa",
        "Bouvet Island": "Americas",
        "Brazil": "Americas",
        "British Indian Ocean Territory": "Africa",
        "Brunei Darussalam": "Asia",
        "Bulgaria": "Europe",
        "Burkina Faso": "Africa",
        "Burundi": "Africa",
        "Cape Verde": "Africa",
        "Cabo Verde": "Africa",
        "Cambodia": "Asia",
        "Cameroon": "Africa",
        "Canada": "Americas",
        "Cayman Islands": "Americas",
        "Central African Republic": "Africa",
        "Chad": "Africa",
        "Chile": "Americas",
        "China": "Asia",
        "Christmas Island": "Oceania",
        "Cocos (Keeling) Islands": "Oceania",
        "Colombia": "Americas",
        "Comoros": "Africa",
        "Congo": "Africa",
        "Democratic Republic of The Congo": "Africa",
        "Cook Islands": "Oceania",
        "Costa Rica": "Americas",
        "Croatia": "Europe",
        "Cuba": "Americas",
        "Curaçao": "Americas",
        "Cyprus": "Asia",
        "Czechia": "Europe",
        "Cote D'ivoire": "Africa",
        "Denmark": "Europe",
        "Djibouti": "Africa",
        "Dominica": "Americas",
        "Dominican Republic": "Americas",
        "Ecuador": "Americas",
        "Egypt": "Africa",
        "El Salvador": "Americas",
        "Equatorial Guinea": "Africa",
        "Eritrea": "Africa",
        "Estonia": "Europe",
        "Swaziland": "Africa",
        "Eswatini": "Africa",
        "Ethiopia": "Africa",
        "Falkland Islands": "Americas",
        "Faroe Islands": "Europe",
        "Fiji": "Oceania",
        "Finland": "Europe",
        "France": "Europe",
        "French Guiana": "Americas",
        "French Polynesia": "Oceania",
        "French Southern Territories": "Africa",
        "Gabon": "Africa",
        "Gambia": "Africa",
        "Georgia": "Asia",
        "Germany": "Europe",
        "Ghana": "Africa",
        "Gibraltar": "Europe",
        "Greece": "Europe",
        "Greenland": "Americas",
        "Grenada": "Americas",
        "Guadeloupe": "Americas",
        "Guam": "Oceania",
        "Guatemala": "Americas",
        "Guernsey": "Europe",
        "Guinea": "Africa",
        "Guinea-Bissau": "Africa",
        "Guyana": "Americas",
        "Haiti": "Americas",
        "Heard Island and Mcdonald Islands": "Oceania",
        "Holy See": "Europe",
        "Honduras": "Americas",
        "Hong Kong": "Asia",
        "Hungary": "Europe",
        "Iceland": "Europe",
        "India": "Asia",
        "Indonesia": "Asia",
        "Iran": "Asia",
        "Iraq": "Asia",
        "Ireland": "Europe",
        "Isle of Man": "Europe",
        "Israel": "Asia",
        "Italy": "Europe",
        "Jamaica": "Americas",
        "Japan": "Asia",
        "Jersey": "Europe",
        "Jordan": "Asia",
        "Kazakhstan": "Asia",
        "Kenya": "Africa",
        "Kiribati": "Oceania",
        "Kosovo": "Europe",
        "North Korea": "Asia",
        "South Korea": "Asia",
        "Kuwait": "Asia",
        "Kyrgyzstan": "Asia",
        "Lao People's Democratic Republic": "Asia",
        "Latvia": "Europe",
        "Lebanon": "Asia",
        "Lesotho": "Africa",
        "Liberia": "Africa",
        "Libya": "Africa",
        "Liechtenstein": "Europe",
        "Lithuania": "Europe",
        "Luxembourg": "Europe",
        "Macao": "Asia",
        "Madagascar": "Africa",
        "Malawi": "Africa",
        "Malaysia": "Asia",
        "Maldives": "Asia",
        "Mali": "Africa",
        "Malta": "Europe",
        "Marshall Islands": "Oceania",
        "Martinique": "Americas",
        "Mauritania": "Africa",
        "Mauritius": "Africa",
        "Mayotte": "Africa",
        "Mexico": "Americas",
        "Micronesia": "Oceania",
        "Moldova": "Europe",
        "Monaco": "Europe",
        "Mongolia": "Asia",
        "Montenegro": "Europe",
        "Montserrat": "Americas",
        "Morocco": "Africa",
        "Mozambique": "Africa",
        "Myanmar": "Asia",
        "Namibia": "Africa",
        "Nauru": "Oceania",
        "Nepal": "Asia",
        "Netherlands": "Europe",
        "Netherlands Antilles": "Americas",
        "New Caledonia": "Oceania",
        "New Zealand": "Oceania",
        "Nicaragua": "Americas",
        "Niger": "Africa",
        "Nigeria": "Africa",
        "Niue": "Oceania",
        "Norfolk Island": "Oceania",
        "Macedonia": "Europe",
        "North Macedonia": "Europe",
        "Northern Mariana Islands": "Oceania",
        "Norway": "Europe",
        "Oman": "Asia",
        "Pakistan": "Asia",
        "Palau": "Oceania",
        "Palestine": "Asia",
        "Panama": "Americas",
        "Papua New Guinea": "Oceania",
        "Paraguay": "Americas",
        "Peru": "Americas",
        "Philippines": "Asia",
        "Pitcairn": "Oceania",
        "Poland": "Europe",
        "Portugal": "Europe",
        "Puerto Rico": "Americas",
        "Qatar": "Asia",
        "Romania": "Europe",
        "Russia": "Europe",
        "Rwanda": "Africa",
        "Réunion": "Africa",
        "Saint Barthélemy": "Americas",
        "Saint Helena": "Africa",
        "Saint Kitts and Nevis": "Americas",
        "Saint Lucia": "Americas",
        "Saint Martin (French Part)": "Americas",
        "Saint Pierre and Miquelon": "Americas",
        "Saint Vincent and The Grenadines": "Americas",
        "Samoa": "Oceania",
        "San Marino": "Europe",
        "Sao Tome and Principe": "Africa",
        "Saudi Arabia": "Asia",
        "Senegal": "Africa",
        "Serbia": "Europe",
        "Seychelles": "Africa",
        "Sierra Leone": "Africa",
        "Singapore": "Asia",
        "Sint Maarten": "Americas",
        "Slovakia": "Europe",
        "Slovenia": "Europe",
        "Solomon Islands": "Oceania",
        "Somalia": "Africa",
        "South Africa": "Africa",
        "South Georgia and The South Sandwich Islands": "Americas",
        "South Sudan": "Africa",
        "Spain": "Europe",
        "Sri Lanka": "Asia",
        "Sudan": "Africa",
        "Suriname": "Americas",
        "Svalbard and Jan Mayen": "Europe",
        "Sweden": "Europe",
        "Switzerland": "Europe",
        "Syria": "Asia",
        "Taiwan": "Asia",
        "Tajikistan": "Asia",
        "Tanzania": "Africa",
        "Thailand": "Asia",
        "Timor-Leste": "Asia",
        "Togo": "Africa",
        "Tokelau": "Oceania",
        "Tonga": "Oceania",
        "Trinidad and Tobago": "Americas",
        "Tunisia": "Africa",
        "Turkey": "Asia",
        "Turkmenistan": "Asia",
        "Turks and Caicos Islands": "Americas",
        "Tuvalu": "Oceania",
        "Uganda": "Africa",
        "Ukraine": "Europe",
        "United Arab Emirates": "Asia",
        "United Kingdom": "Europe",
        "United States Minor Outlying Islands": "Oceania",
        "United States": "Americas",
        "Uruguay": "Americas",
        "Uzbekistan": "Asia",
        "Vanuatu": "Oceania",
        "Venezuela": "Americas",
        "Vietnam": "Asia",
        "Virgin Islands (British)": "Americas",
        "Virgin Islands (U.S.)": "Americas",
        "Wallis and Futuna": "Oceania",
        "Western Sahara": "Africa",
        "Yemen": "Asia",
        "Zambia": "Africa",
        "Zimbabwe": "Africa",
        "Åland Islands": "Europe",
    }
)
