SCIENTIFIC_AND_ACADEMIC = frozenset(
    [
        "abstract",
        "abstracts",
        "accuracy",
        "algorithmic",
        "analyses",
        "analysis",
        "annotation",
        "annotations",
        "appendices",
        "appendix",
        "approach",
        "approaches",
        "article",
        "articles",
        "assessment",
        "assessments",
        "author",
        "authors",
        "baseline",
        "benchmark",
        "benchmarks",
        "bias",
        "biases",
        "bibliographic",
        "bibliographies",
        "bibliography",
        "bibliometric",
        "bibliometrics",
        "book",
        "books",
        "case report",
        "case reports",
        "case series",
        "case studies",
        "case study",
        "chapter",
        "chapters",
        "checklist",
        "checklists",
        "citation",
        "citations",
        "classification",
        "classifications",
        "clinical study",
        "clinical studies",
        "clinical trial",
        "clinical trials",
        "cluster analysis",
        "clustering",
        "coding",
        "cohort",
        "cohorts",
        "cohort study",
        "cohort studies",
        "collection",
        "collections",
        "commentary",
        "commentaries",
        "comparative",
        "comparative studies",
        "comparative study",
        "computer simulation",
        "computer simulations",
        "concept",
        "concepts",
        "conclusion",
        "conclusions",
        "conference",
        "conferences",
        "confusion matrix",
        "content analysis",
        "contribution",
        "contributions",
        "control",
        "controls",
        "controlled studies",
        "controlled study",
        "correlation",
        "correlations",
        "covariate",
        "covariates",
        "criteria",
        "criterion",
        "cross-sectional",
        "cross-sectional study",
        "cross-sectional studies",
        "cross-validation",
        "data",
        "database",
        "databases",
        "dataset",
        "datasets",
        "dependent variable",
        "dependent variables",
        "descriptive",
        "descriptive statistics",
        "design",
        "designs",
        "discussion",
        "discussions",
        "distribution",
        "distributions",
        "document",
        "documents",
        "editorial",
        "editorials",
        "effect size",
        "empirical",
        "empirical studies",
        "empirical study",
        "endpoint",
        "endpoints",
        "error",
        "errors",
        "ethnographic",
        "ethnography",
        "evaluation",
        "evaluations",
        "evidence",
        "examination",
        "examinations",
        "exclusion criteria",
        "experiment",
        "experiments",
        "experimental",
        "experimental data",
        "experimental studies",
        "experimental study",
        "exploration",
        "explorations",
        "f1 score",
        "factor",
        "factors",
        "feature extraction",
        "feature selection",
        "field study",
        "field studies",
        "figure",
        "figures",
        "finding",
        "findings",
        "focus group",
        "focus groups",
        "follow-up",
        "forecast",
        "forecasting",
        "framework",
        "frameworks",
        "ground truth",
        "grounded theory",
        "guideline",
        "guidelines",
        "heterogeneity",
        "hypotheses",
        "hypothesis",
        "implication",
        "implications",
        "inclusion criteria",
        "independent variable",
        "independent variables",
        "index",
        "indexes",
        "indices",
        "indicator",
        "indicators",
        "informant",
        "informants",
        "instrumentation",
        "intercept",
        "intervention",
        "interventions",
        "interview",
        "interviews",
        "introduction",
        "introductions",
        "investigation",
        "investigations",
        "journal",
        "journals",
        "limitation",
        "limitations",
        "linear regression",
        "literature",
        "literature review",
        "literature reviews",
        "logistic regression",
        "longitudinal studies",
        "longitudinal study",
        "manuscript",
        "manuscripts",
        "measure",
        "measurement",
        "measurements",
        "measures",
        "meta-analysis",
        "meta-analyses",
        "method",
        "methodologies",
        "methodology",
        "methods",
        "metric",
        "metrics",
        "mixed methods",
        "model",
        "modeling",
        "modelling",
        "models",
        "narrative",
        "narratives",
        "null hypothesis",
        "objective",
        "objectives",
        "observation",
        "observations",
        "observational",
        "observational data",
        "observational studies",
        "observational study",
        "optimization",
        "outcome",
        "outcomes",
        "outlier",
        "outliers",
        "overview",
        "overviews",
        "p-value",
        "panel study",
        "panel studies",
        "paper",
        "papers",
        "participant",
        "participants",
        "phenomenological",
        "phenomenology",
        "pilot",
        "pilot studies",
        "pilot study",
        "population",
        "populations",
        "precision",
        "prediction",
        "predictions",
        "predictive model",
        "predictive models",
        "primary data",
        "principal component analysis",
        "procedure",
        "procedures",
        "proceedings",
        "prospective",
        "protocol",
        "protocols",
        "publication",
        "publications",
        "qualitative",
        "qualitative data",
        "qualitative research",
        "quality control",
        "quantitative",
        "quantitative data",
        "quantitative research",
        "quasi-experimental",
        "questionnaire",
        "questionnaires",
        "randomized",
        "randomized controlled trial",
        "randomized controlled trials",
        "rct",
        "recall",
        "receiver operating characteristic",
        "reference",
        "references",
        "regression",
        "regression analysis",
        "regression model",
        "reliability",
        "replication",
        "report",
        "reports",
        "research",
        "research question",
        "research questions",
        "respondent",
        "respondents",
        "result",
        "results",
        "retrospective",
        "review",
        "reviews",
        "risk assessment",
        "roc",
        "roc curve",
        "sample",
        "sample size",
        "samples",
        "sampling",
        "scholarly",
        "scoping review",
        "scoping reviews",
        "score",
        "scores",
        "secondary data",
        "semi-structured",
        "semi-structured interview",
        "sensitivity",
        "sensitivity analysis",
        "significance",
        "significant",
        "simulation",
        "simulations",
        "specificity",
        "standardization",
        "stata",
        "statistical",
        "statistical analysis",
        "statistical model",
        "statistics",
        "statistical test",
        "strategies",
        "strategy",
        "structured",
        "studies",
        "study",
        "subject",
        "subjects",
        "supplementary",
        "survey",
        "surveys",
        "systematic review",
        "systematic reviews",
        "t-test",
        "table",
        "tables",
        "technique",
        "techniques",
        "test",
        "test set",
        "testing",
        "tests",
        "textbook",
        "textbooks",
        "thematic analysis",
        "theoretical",
        "theories",
        "theory",
        "thesis",
        "theses",
        "training data",
        "training set",
        "transcript",
        "transcripts",
        "treatment",
        "treatments",
        "trial",
        "trials",
        "triangulation",
        "univariate",
        "unstructured",
        "validation",
        "validation set",
        "validity",
        "variable",
        "variables",
        "variance",
        "verification",
    ]
)
