STOPWORDS = frozenset(
    [
        "a",
        "able",
        "about",
        "above",
        "accordance",
        "according",
        "accordingly",
        "across",
        "after",
        "afterwards",
        "again",
        "against",
        "al",
        "all",
        "almost",
        "alone",
        "along",
        "already",
        "also",
        "alternatively",
        "although",
        "always",
        "am not",
        "am",
        "among",
        "amongst",
        "amoungst",
        "amount",
        "an",
        "and",
        "and/or",
        "another",
        "any",
        "anyhow",
        "anyone",
        "anything",
        "anyway",
        "anywhere",
        "are not",
        "are",
        "around",
        "as",
        "at",
        "back",
        "be",
        "became",
        "because",
        "become",
        "becomes",
        "becoming",
        "been",
        "before",
        "beforehand",
        "behind",
        "being",
        "below",
        "beside",
        "besides",
        "better",
        "between",
        "beyond",
        "bill",
        "both",
        "bottom",
        "but",
        "by",
        "call",
        "can not",
        "can",
        "cannot",
        "cant",
        "case",
        "claim",
        "co",
        "compared",
        "comprises",
        "con",
        "corresponding",
        "could not",
        "could",
        "couldnt",
        "cry",
        "current",
        "d",
        "de",
        "describe",
        "described",
        "desired",
        "detail",
        "did not",
        "did",
        "different",
        "disclosure",
        "do not",
        "do",
        "does not",
        "does",
        "doing",
        "done",
        "down",
        "due",
        "during",
        "each",
        "easily",
        "easy",
        "eg",
        "eight",
        "either",
        "eleven",
        "else",
        "elsewhere",
        "embodiment",
        "empty",
        "enough",
        "especially",
        "essentially",
        "et",
        "etc",
        "even",
        "eventually",
        "ever",
        "every",
        "everyone",
        "everything",
        "everywhere",
        "excellent",
        "except",
        "existing",
        "few",
        "fifteen",
        "fifty",
        "fig",
        "figs",
        "fill",
        "finally",
        "find",
        "fire",
        "first",
        "five",
        "following",
        "for",
        "former",
        "formerly",
        "forty",
        "forward",
        "found",
        "four",
        "from",
        "front",
        "full",
        "further",
        "furthermore",
        "generally",
        "get",
        "give",
        "go",
        "good",
        "had not",
        "had",
        "half",
        "has not",
        "has",
        "hasnt",
        "have not",
        "have",
        "having",
        "he is",
        "he will",
        "he would",
        "he",
        "he/she",
        "hence",
        "her",
        "here is",
        "here",
        "hereafter",
        "hereby",
        "herein",
        "hereupon",
        "hers",
        "herself",
        "him",
        "him/her",
        "himself",
        "his",
        "his/her",
        "how is",
        "how",
        "however",
        "hundred",
        "i am",
        "i have",
        "i will",
        "i would",
        "i",
        "ie",
        "if",
        "ii",
        "iii",
        "important",
        "in",
        "inc",
        "including",
        "indeed",
        "inf",
        "instead",
        "interest",
        "into",
        "invention",
        "is not",
        "is",
        "it is",
        "it",
        "its",
        "itself",
        "just",
        "keep",
        "large",
        "last",
        "later",
        "latter",
        "latterly",
        "least",
        "less",
        "let us",
        "level",
        "like",
        "little",
        "ltd",
        "m",
        "ma",
        "made",
        "make",
        "many",
        "may",
        "me",
        "means",
        "meanwhile",
        "mentioned",
        "might not",
        "might",
        "mill",
        "mine",
        "more",
        "moreover",
        "most",
        "mostly",
        "move",
        "much",
        "must not",
        "must",
        "my",
        "myself",
        "name",
        "namely",
        "need not",
        "need",
        "neither",
        "never",
        "nevertheless",
        "new",
        "next",
        "nine",
        "no",
        "nobody",
        "none",
        "noone",
        "nor",
        "not",
        "nothing",
        "now",
        "nowhere",
        "o",
        "of",
        "off",
        "often",
        "on",
        "once",
        "one",
        "ones",
        "only",
        "onto",
        "or",
        "other",
        "others",
        "otherwise",
        "ought",
        "our",
        "ours",
        "ourselves",
        "out",
        "over",
        "overall",
        "own",
        "part",
        "particularly",
        "per",
        "perhaps",
        "please",
        "preferably",
        "preferred",
        "present",
        "provide",
        "provided",
        "provides",
        "put",
        "quite",
        "rather",
        "re",
        "really",
        "regarding",
        "relatively",
        "remarkably",
        "respectively",
        "s",
        "said",
        "same",
        "say",
        "see",
        "seem",
        "seemed",
        "seeming",
        "seems",
        "serious",
        "several",
        "shall not",
        "shall",
        "shan not",
        "she is",
        "she will",
        "she would",
        "she",
        "should not",
        "should",
        "show",
        "side",
        "significant",
        "significantly",
        "simply",
        "since",
        "sincere",
        "six",
        "sixty",
        "so",
        "some",
        "somebody",
        "somehow",
        "someone",
        "something",
        "sometime",
        "sometimes",
        "somewhere",
        "specifically",
        "still",
        "straight",
        "substantially",
        "such",
        "sufficient",
        "suitable",
        "system",
        "t",
        "take",
        "ten",
        "than",
        "that is",
        "that will",
        "that'll",
        "that",
        "the",
        "their",
        "theirs",
        "them",
        "themselves",
        "then",
        "thence",
        "there is",
        "there",
        "thereafter",
        "therebetween",
        "thereby",
        "therefor",
        "therefore",
        "therefrom",
        "therein",
        "thereinto",
        "thereof",
        "thereon",
        "therethrough",
        "thereto",
        "thereupon",
        "therewith",
        "these",
        "they are",
        "they have",
        "they will",
        "they would",
        "they",
        "thick",
        "thin",
        "third",
        "this",
        "those",
        "though",
        "three",
        "thrice",
        "through",
        "throughout",
        "thru",
        "thus",
        "to",
        "together",
        "too",
        "top",
        "total",
        "toward",
        "towards",
        "twelve",
        "twenty",
        "twice",
        "two",
        "typical",
        "un",
        "under",
        "unless",
        "until",
        "up",
        "upon",
        "us",
        "use",
        "used",
        "using",
        "usually",
        "various",
        "versa",
        "very",
        "via",
        "vice",
        "viceversa",
        "was not",
        "was",
        "we are",
        "we have",
        "we will",
        "we would",
        "we",
        "well",
        "were not",
        "were",
        "what is",
        "what",
        "whatever",
        "when is",
        "when",
        "whence",
        "whenever",
        "where is",
        "where",
        "whereafter",
        "whereas",
        "whereat",
        "whereby",
        "wherein",
        "whereupon",
        "wherever",
        "whether",
        "which",
        "whichever",
        "while",
        "whilst",
        "whither",
        "who is",
        "who",
        "whoever",
        "whole",
        "whom",
        "whomever",
        "whose",
        "why is",
        "why",
        "will not",
        "will",
        "with",
        "within",
        "without",
        "would not",
        "would",
        "y",
        "yet",
        "you are",
        "you have",
        "you will",
        "you would",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
    ]
)
