"""TechMiner 2"""
from .bibliometrix.overview.bibliometrix__annual_scientific_production import (
    bibliometrix__annual_scientific_production,
)
from .bibliometrix.overview.bibliometrix__main_information import (
    bibliometrix__main_information,
)
from .bibliometrix__author_impact import bibliometrix__author_impact
from .bibliometrix__authors_production_over_time import (
    bibliometrix__authors_production_over_time,
)
from .bibliometrix__average_citations_per_year import (
    bibliometrix__average_citations_per_year,
)
from .bibliometrix__bradford_law import bibliometrix__bradford_law
from .bibliometrix__co_authorship_network import bibliometrix__co_authorship_network
from .bibliometrix__co_citation_matrix_list import bibliometrix__co_citation_matrix_list
from .bibliometrix__co_citation_network import bibliometrix__co_citation_network
from .bibliometrix__co_occurrence_network import bibliometrix__co_occurrence_network
from .bibliometrix__collaboration_worldmap import bibliometrix__collaboration_worldmap
from .bibliometrix__corresponding_authors_country import (
    bibliometrix__corresponding_authors_country,
)
from .bibliometrix__countries_production_over_time import (
    bibliometrix__countries_production_over_time,
)
from .bibliometrix__country_dynamics import bibliometrix__country_dynamics
from .bibliometrix__country_impact import bibliometrix__country_impact
from .bibliometrix__country_scientific_production import (
    bibliometrix__country_scientific_production,
)
from .bibliometrix__coupling_matrix_list import bibliometrix__coupling_matrix_list
from .bibliometrix__coupling_network import bibliometrix__coupling_network
from .bibliometrix__factorial_analysis import bibliometrix__factorial_analysis_with_mds
from .bibliometrix__lotka_law import bibliometrix__lotka_law
from .bibliometrix__most_frequent_authors import bibliometrix__most_frequent_authors
from .bibliometrix__most_frequent_countries import bibliometrix__most_frequent_countries
from .bibliometrix__most_frequent_words import bibliometrix__most_frequent_words
from .bibliometrix__most_global_cited_authors import (
    bibliometrix__most_global_cited_authors,
)
from .bibliometrix__most_global_cited_countries import (
    bibliometrix__most_global_cited_countries,
)
from .bibliometrix__most_global_cited_documents import (
    bibliometrix__most_global_cited_documents,
)
from .bibliometrix__most_global_cited_organizations import (
    bibliometrix__most_global_cited_organizations,
)
from .bibliometrix__most_global_cited_references import (
    bibliometrix__most_global_cited_references,
)
from .bibliometrix__most_global_cited_sources import (
    bibliometrix__most_global_cited_sources,
)
from .bibliometrix__most_local_cited_authors import (
    bibliometrix__most_local_cited_authors,
)
from .bibliometrix__most_local_cited_countries import (
    bibliometrix__most_local_cited_countries,
)
from .bibliometrix__most_local_cited_documents import (
    bibliometrix__most_local_cited_documents,
)
from .bibliometrix__most_local_cited_organizations import (
    bibliometrix__most_local_cited_organizations,
)
from .bibliometrix__most_local_cited_references import (
    bibliometrix__most_local_cited_references,
)
from .bibliometrix__most_local_cited_sources import (
    bibliometrix__most_local_cited_sources,
)
from .bibliometrix__most_relevant_organizations import (
    bibliometrix__most_relevant_organizations,
)
from .bibliometrix__most_relevant_sources import bibliometrix__most_relevant_sources
from .bibliometrix__organization_impact import bibliometrix__organization_impact
from .bibliometrix__organizations_production_over_time import (
    bibliometrix__organizations_production_over_time,
)
from .bibliometrix__rpys import bibliometrix__rpys
from .bibliometrix__source_dynamics import bibliometrix__source_dynamics
from .bibliometrix__source_impact import bibliometrix__source_impact
from .bibliometrix__sources_production_over_time import (
    bibliometrix__sources_production_over_time,
)
from .bibliometrix__thematic_evolution_plot import bibliometrix__thematic_evolution_plot
from .bibliometrix__thematic_map import bibliometrix__thematic_map
from .bibliometrix__three_fields_plot import bibliometrix__three_fields_plot
from .bibliometrix__treemap import bibliometrix__treemap
from .bibliometrix__trend_topics import bibliometrix__trend_topics
from .bibliometrix__word_cloud import bibliometrix__word_cloud
from .bibliometrix__word_dynamics import bibliometrix__word_dynamics
from .scientopy__bar import scientopy__bar
from .scientopy__bar_trends import scientopy__bar_trends
from .scientopy__time_line import scientopy__time_line
from .scientopy__top_trending_topics import scientopy__top_trending_topics
from .scientopy__word_cloud import scientopy__word_cloud
from .tlab__co_occurrence_analysis__co_word_analysis import (
    tlab__co_occurrence_analysis__co_word_analysis,
)
from .tlab__co_occurrence_analysis__comparison_between_topics import (
    tlab__co_occurrence_analysis__comparison_between_topics,
)
from .tlab__co_occurrence_analysis__concordances import (
    tlab__co_occurrence_analysis__concordances,
)
from .tlab__comparative_analysis__svd_of_co_occ_matrix import (
    tlab__comparative_analysis__svd_of_co_occ_matrix,
)
from .tlab__comparative_analysis__svd_of_tf_matrix import (
    tlab__comparative_analysis__svd_of_tf_matrix,
)
from .tlab__lexical_tools__text_screening import tlab__lexical_tools__text_screening
from .tlab__thematic_analysis__elementary_contexts import (
    tlab__thematic_analysis__elementary_contexts,
)
from .tlab__thematic_analysis__emergent_themes import (
    tlab__thematic_analysis__emergent_themes_with_lda,
    tlab__thematic_analysis__emergent_themes_with_nmf,
)
from .tlab__word_associations_co_occurrences_plot import (
    tlab__word_associations_co_occurrences_plot,
)
from .tlab__word_associations_for_a_item import tlab__word_associations_for_a_item
from .tlab__word_associations_for_all_items import tlab__word_associations_for_all_items
from .tlab__word_associations_mds_map import tlab__word_associations_mds_map
from .tlab__word_associations_radial_diagram import (
    tlab__word_associations_radial_diagram,
)
from .tm2__abstracts_report import tm2__abstracts_report
from .tm2__annual_occurrence_matrix import tm2__annual_occurrence_matrix
from .tm2__collaboration_indicators_by_topic import (
    tm2__collaboration_indicators_by_topic,
)
from .tm2__coverage import tm2__coverage
from .tm2__extractive_summarization import tm2__extractive_summarization
from .tm2__growth_indicators_by_topic import tm2__growth_indicators_by_topic
from .tm2__impact_indicators_by_topic import tm2__impact_indicators_by_topic
from .tm2__indicators_by_document import tm2__indicators_by_document
from .tm2__indicators_by_topic import tm2__indicators_by_topic
from .tm2__indicators_by_topic_per_year import tm2__indicators_by_topic_per_year
from .tm2__indicators_by_year import tm2__indicators_by_year
from .tm2__most_cited_documents import tm2__most_cited_documents
from .tm2__raw_document_types import tm2__raw_document_types
from .tm2__replace import tm2__replace
from .vantagepoint__auto_corr_matrix_list import vantagepoint__auto_corr_matrix_list
from .vantagepoint__bar_chart import vantagepoint__bar_chart
from .vantagepoint__bubble_chart import vantagepoint__bubble_chart
from .vantagepoint__cleveland_chart import vantagepoint__cleveland_chart
from .vantagepoint__column_chart import vantagepoint__column_chart
from .vantagepoint__cross_corr_matrix import vantagepoint__cross_corr_matrix
from .vantagepoint__cross_corr_matrix_list import vantagepoint__cross_corr_matrix_list
from .vantagepoint__factor_matrix import vantagepoint__factor_matrix
from .vantagepoint__gantt_chart import vantagepoint__gantt_chart
from .vantagepoint__heat_map import vantagepoint__heat_map
from .vantagepoint__line_chart import vantagepoint__line_chart
from .vantagepoint__matrix_viewer import vantagepoint__matrix_viewer
from .vantagepoint__occ_matrix import vantagepoint__occ_matrix
from .vantagepoint__occ_matrix_list import vantagepoint__occ_matrix_list
from .vantagepoint__pie_chart import vantagepoint__pie_chart
from .vantagepoint__tf_idf_matrix import vantagepoint__tf_idf_matrix
from .vantagepoint__tf_matrix import vantagepoint__tf_matrix
from .vantagepoint__treemap import vantagepoint__treemap
from .vantagepoint__word_cloud import vantagepoint__word_cloud
from .vantagepoint__world_map import vantagepoint__world_map
