"""Data types for columns in Scopus"""

DTYPES = {
    "Abbreviated Source Title": str,
    "Abstract": str,
    "Affiliations": str,
    "Art. No.": str,
    "Author full names": str,
    "Author Keywords": str,
    "Author(s) ID": str,
    "Authors with affiliations": str,
    "Authors": str,
    "Chemicals/CAS": str,
    "Cited by": int,
    "CODEN": str,
    "Conference code": str,
    "Conference date": str,
    "Conference location": str,
    "Conference name": str,
    "Correspondence Address": str,
    "Document Type": str,
    "DOI": str,
    "Editors": str,
    "EID": str,
    "Funding Details": str,
    "Funding Texts": str,
    "Index Keywords": str,
    "ISBN": str,
    "ISSN": str,
    "Issue": str,
    "Language of Original Document": str,
    "Link": str,
    "Manufacturers": str,
    "Molecular Sequence Numbers": str,
    "Open Access": str,
    "Page count": str,
    "Page end": str,
    "Page start": str,
    "Publication Stage": str,
    "Publisher": str,
    "PubMed ID": str,
    "References": str,
    "Source title": str,
    "Source": str,
    "Sponsors": str,
    "Title": str,
    "Tradenames": str,
    "Volume": str,
    "Year": int,
    #
    "abbr_source_title": str,
    "abstract": str,
    "affiliations": str,
    "art_no": str,
    "author_full_names": str,
    "raw_author_keywords": str,
    "raw_authors_id": str,
    "authors_with_affiliations": str,
    "raw_authors": str,
    "casregnumber": str,
    "global_citations": int,
    "coden": str,
    "conference_code": str,
    "conference_date": str,
    "conference_location": str,
    "conference_name": str,
    "correspondence_address": str,
    "raw_document_type": str,
    "doi": str,
    "editors": str,
    "eid": str,
    "funding_details": str,
    "funding_texts": str,
    "raw_index_keywords": str,
    "isbn": str,
    "issn": str,
    "issue": str,
    "language": str,
    "link": str,
    "manufacturers": str,
    "molecular_sequence_numbers": str,
    "open_access": str,
    "page_count": str,
    "page_end": str,
    "page_start": str,
    "publication_stage": str,
    "publisher": str,
    "pubmed": str,
    "raw_global_references": str,
    "source_title": str,
    "source": str,
    "sponsors": str,
    "title": str,
    "tradenames": str,
    "volume": str,
    "year": int,
}
