from enum import Enum


class CorpusField(Enum):

    UNSPECIFIED = "_UNSPECIFIED_"

    #
    # A
    #
    ABS_RAW = "ABS_RAW"
    ABS_TOK = "ABS_TOK"
    ABS_TOK_WITH_UPPER_NP = "ABS_TOK_WITH_UPPER_NP"
    ABS_TOK_WITH_UPPER_WORD = "ABS_TOK_WITH_UPPER_WORD"
    ABS_NP_TOK = "ABS_NP_TOK"
    ABS_WORD_TOK = "ABS_WORD_TOK"
    ACRONYM = "ACRONYM"
    AFFIL_RAW = "AFFIL_RAW"
    ART_NO = "ART_NO"
    AUTH_AFFIL = "AUTH_AFFIL"
    AUTH_DISAMB = "AUTH_DISAMB"
    AUTH_FULL = "AUTH_FULL"
    AUTH_ID_NORM = "AUTH_ID_NORM"
    AUTH_ID_RAW = "AUTH_ID_RAW"
    AUTH_KEY_NORM = "AUTH_KEY_NORM"
    AUTH_KEY_RAW = "AUTH_KEY_RAW"
    AUTH_KEY_TOK = "AUTH_KEY_TOK"
    AUTH_NORM = "AUTH_NORM"
    AUTH_RAW = "AUTH_RAW"

    #
    # C
    #
    CAS_REG_NUMBER = "CAS_REG_NUMBER"
    CIT_COUNT_GLOBAL = "CIT_COUNT_GLOBAL"
    CIT_COUNT_LOCAL = "CIT_COUNT_LOCAL"
    CODEN = "CODEN"
    CONF_CODE = "CONF_CODE"
    CONF_DATE = "CONF_DATE"
    CONF_LOC = "CONF_LOC"
    CONF_NAME = "CONF_NAME"
    CORRESP = "CORRESP"
    COUNTRY = "COUNTRY"
    COUNTRY_FIRST_AUTH = "COUNTRY_FIRST_AUTH"
    COUNTRY_AND_AFFIL = "COUNTRY_AND_AFFIL"

    #
    # D
    #
    DOC_TITLE_NP_NORM = "DOC_TITLE_NP_NORM"
    DOC_TITLE_NP_TOK = "DOC_TITLE_NP_TOK"
    DOC_TITLE_RAW = "DOC_TITLE_RAW"
    DOC_TITLE_TOK = "DOC_TITLE_TOK"
    DOC_TITLE_TOK_WITH_UPPER_NP = "DOC_TITLE_TOK_WITH_UPPER_NP"
    DOC_TITLE_TOK_WITH_UPPER_WORD = "DOC_TITLE_TOK_WITH_UPPER_WORD"
    DOC_TITLE_WORD_TOK = "DOC_TITLE_WORD_TOK"
    DOC_TYPE_NORM = "DOC_TYPE_NORM"
    DOC_TYPE_RAW = "DOC_TYPE_RAW"
    DOI = "DOI"

    #
    # E
    #
    EDITOR = "EDITOR"
    EID = "DOC_IDENTIFIER"
    EISSN = "EISSN"

    #
    # F
    #
    FIRST_AUTH = "FIRST_AUTH"
    DESCRIPTOR_TOK = "DESCRIPTOR_TOK"
    DESCRIPTOR_NORM = "DESCRIPTOR_NORM"
    FUND_DETAILS = "FUND_DETAILS"
    FUND_SPONSORS = "FUND_SPONSORS"
    FUND_TEXTS = "FUND_TEXTS"

    #
    # H
    #
    HYB_KEY_NORM = "HYB_KEY_NORM"
    HYB_KEY_TOK = "HYB_KEY_TOK"

    #
    # I
    #
    IDX_KEY_NORM = "IDX_KEY_NORM"
    IDX_KEY_RAW = "IDX_KEY_RAW"
    IDX_KEY_TOK = "IDX_KEY_TOK"
    ISBN = "ISBN"
    ISSN = "ISSN"
    ISSNP = "ISSNP"
    ISSUE = "ISSUE"

    #
    # K
    #
    KEY_NORM = "KEY_NORM"

    KEY_TOK = "KEY_TOK"
    KEY_AND_WORD_NORM = "KEY_AND_WORD_NORM"
    KEY_AND_WORD_TOK = "KEY_AND_WORD_TOK"

    #
    # L
    #
    LANGUAGE = "LANGUAGE"
    LINK = "LINK"

    #
    # M
    #
    MANUFACTURER = "MANUFACTURER"

    #
    # N
    #
    NP_NORM = "NP_NORM"
    NP_TOK = "NP_TOK"
    NUM_AUTH = "NUM_AUTH"
    NUM_REF_GLOBAL = "NUM_REF_GLOBAL"
    NUM_REF_LOCAL = "NUM_REF_LOCAL"

    #
    # O
    #
    OA = "OPEN_ACCESS"
    ORGANIZATION = "ORGANIZATION"
    ORGANIZATION_FIRST_AUTH = "ORGANIZATION_FIRST_AUTH"
    ORGANIZATION_AND_AFFIL = "ORGANIZATION_AND_AFFIL"

    #
    # P
    #
    PAGE_FIRST = "PAGE_FIRST"
    PAGE_LAST = "PAGE_LAST"
    PAGE_COUNT = "PAGE_COUNT"
    PUBLISHER = "PUBLISHER"
    PUBMED = "PUBMED"
    PUBSTAGE = "PUBSTAGE"
    PUBYEAR = "PUBYEAR"

    #
    # R
    #
    REC_ID = "REC_ID"
    REC_NO = "REC_NO"
    REF_NORM = "REF_NORM"
    REF_AND_REC_ID = "REF_AND_REC_ID"
    REF_RAW = "REF_RAW"
    REGION = "REGION"

    #
    # S
    #
    SPACY = "SPACY"
    SEQ_NUMBER = "SEQ_NUMBER"
    SOURCE = "SOURCE"
    SRC_TITLE_ABBR_NORM = "SRC_TITLE_ABBR_NORM"
    SRC_TITLE_ABBR_RAW = "SRC_TITLE_ABBR_RAW"
    SRC_TITLE_NORM = "SRC_TITLE_NORM"
    SRC_TITLE_RAW = "SRC_TITLE_RAW"
    SUBJ_AREA = "SUBJ_AREA"
    SUBREGION = "SUBREGION"

    #
    # T
    #
    TRADENAME = "TRADENAME"
    TEXTBLOB = "TEXTBLOB"

    #
    # V
    #
    VOL = "VOL"

    #
    # W
    #
    WORD_NORM = "WORD_NORM"
    WORD_TOK = "WORD_TOK"

    #
    # User fields
    #
    USER_0 = "USER_0"
    USER_1 = "USER_1"
    USER_2 = "USER_2"
    USER_3 = "USER_3"
    USER_4 = "USER_4"
    USER_5 = "USER_5"
    USER_6 = "USER_6"
    USER_7 = "USER_7"
    USER_8 = "USER_8"
    USER_9 = "USER_9"


class ItemsOrderBy(Enum):

    OCC = "OCC"
    CIT_COUNT_GLOBAL = "CIT_COUNT_GLOBAL"
    CIT_COUNT_LOCAL = "CIT_COUNT_LOCAL"


class RecordsOrderBy(Enum):

    CIT_COUNT_GLOBAL_BY_HIGHEST = "cit_count_global_by_highest"
    CIT_COUNT_GLOBAL_BY_LOWEST = "cit_count_global_by_lowest"
    CIT_COUNT_LOCAL_BY_HIGHEST = "cit_count_local_by_highest"
    CIT_COUNT_LOCAL_BY_LOWEST = "cit_count_local_by_lowest"
    FIRST_AUTH_A_TO_Z = "first_auth_a_to_z"
    FIRST_AUTH_Z_TO_A = "first_auth_z_to_a"
    PUBYEAR_NEWEST = "pubyear_newest"
    PUBYEAR_OLDEST = "pubyear_oldest"
    SRC_TITLE_A_TO_Z = "src_title_a_to_z"
    SRE_TITLE_Z_TO_A = "src_title_z_to_a"


class ThesaurusField(Enum):

    CHANGED = "CHANGED"
    IS_KEYWORD = "IS_KEYWORD"
    OCC = "OCC"
    OLD = "OLD"
    PREFERRED = "PREFERRED_TERM"
    SIGNATURE = "SIGNATURE"
    VARIANT = "VARIANT"
