from ._core.compute_cosine_similarities_from_tfidf_svd_embedding import compute_cosine_similarities_from_tfidf_svd_embedding
from ._core.compute_tfidf_svd_embedding import compute_tfidf_svd_embedding
from ._core.plot_2d_map_from_tfidf_svd_embedding import plot_2d_map_from_tfidf_svd_embedding
from ._core.plot_tsne_map_from_tfidf_svd_embedding import plot_tsne_map_from_tfidf_svd_embedding
