_COUNTRY_REPLACEMENTS = [
    ("Bosnia and Herz.", "Bosnia and Herzegovina"),
    ("Brasil", "Brazil"),
    ("Central African Rep.", "Central African Republic"),
    ("Congo, Democratic Republic of The", "Democratic Republic of The Congo"),
    ("Côte D'Ivoire", "Cote D'Ivoire"),
    ("Czech Republic", "Czechia"),
    ("Dem. Rep. Congo", "Democratic Republic of The Congo"),
    ("Dominican Rep.", "Dominican Republic"),
    ("England", "United Kingdom"),
    ("Eq. Guinea", "Equatorial Guinea"),
    ("Espana", "Spain"),
    ("Falkland Is.", "Falkland Islands"),
    ("Macao", "China"),
    ("Macau", "China"),
    ("N. Cyprus", "Cyprus"),
    ("Palestine, State Of", "Palestine"),
    ("Peoples R China", "China"),
    ("P R China", "China"),
    ("Perú", "Peru"),
    ("Rusia", "Russia"),
    ("Moscow", "Russia"),
    ("Republic of Ireland", "Ireland"),
    ("Russian Federation", "Russia"),
    ("Saint Helena, Ascension and Tristan Da Cunha", "Saint Helena"),
    ("Solomon Is.", "Solomon Islands"),
    ("St. Kitts and Nevis", "Saint Kitts and Nevis"),
    ("St. Lucia", "Saint Lucia"),
    ("St. Vincent and The Grenadines", "Saint Vincent and The Grenadines"),
    ("Syrian Arab Republic", "Syria"),
    ("The Netherlands", "Netherlands"),
    ("The Philippines", "Philippines"),
    ("Trinidad & Tobago", "Trinidad and Tobago"),
    ("Türkiye", "Turkey"),
    ("United States of America", "United States"),
    ("USA", "United States"),
    ("U.S.A", "United States"),
    ("Viet Nam", "Vietnam"),
    ("Viet-Nam", "Vietnam"),
    ("W. Sahara", "Western Sahara"),
    #
    ("Alabama", "United States"),
    ("Alaska", "United States"),
    ("Arizona", "United States"),
    ("Arkansas", "United States"),
    ("California", "United States"),
    ("Colorado", "United States"),
    ("Connecticut", "United States"),
    ("Delaware", "United States"),
    ("Florida", "United States"),
    ("Georgia", "United States"),
    ("Hawaii", "United States"),
    ("Idaho", "United States"),
    ("Illinois", "United States"),
    ("Indiana", "United States"),
    ("Iowa", "United States"),
    ("Kansas", "United States"),
    ("Kentucky", "United States"),
    ("Louisiana", "United States"),
    ("Maine", "United States"),
    ("Maryland", "United States"),
    ("Massachusetts", "United States"),
    ("Michigan", "United States"),
    ("Minnesota", "United States"),
    ("Mississippi", "United States"),
    ("Missouri", "United States"),
    ("Montana", "United States"),
    ("Nebraska", "United States"),
    ("Nevada", "United States"),
    ("New Hampshire", "United States"),
    ("New Jersey", "United States"),
    ("New Mexico", "United States"),
    ("New York", "United States"),
    ("North Carolina", "United States"),
    ("North Dakota", "United States"),
    ("Ohio", "United States"),
    ("Oklahoma", "United States"),
    ("Oregon", "United States"),
    ("Pennsylvania", "United States"),
    ("Rhode Island", "United States"),
    ("South Carolina", "United States"),
    ("South Dakota", "United States"),
    ("Tennessee", "United States"),
    ("Texas", "United States"),
    ("Utah", "United States"),
    ("Vermont", "United States"),
    ("Virginia", "United States"),
    ("Washington", "United States"),
    ("West Virginia", "United States"),
    ("Wisconsin", "United States"),
    ("Wyoming", "United States"),
    ("District of Columbia", "United States"),
    #
    ("AL", "United States"),
    ("AK", "United States"),
    ("AZ", "United States"),
    ("AR", "United States"),
    ("CA", "United States"),
    ("CO", "United States"),
    ("CT", "United States"),
    ("DE", "United States"),
    ("FL", "United States"),
    ("GA", "United States"),
    ("HI", "United States"),
    ("ID", "United States"),
    ("IL", "United States"),
    ("IN", "United States"),
    ("IA", "United States"),
    ("KS", "United States"),
    ("KY", "United States"),
    ("LA", "United States"),
    ("ME", "United States"),
    ("MD", "United States"),
    ("MA", "United States"),
    ("MI", "United States"),
    ("MN", "United States"),
    ("MS", "United States"),
    ("MO", "United States"),
    ("MT", "United States"),
    ("NE", "United States"),
    ("NV", "United States"),
    ("NH", "United States"),
    ("NJ", "United States"),
    ("NM", "United States"),
    ("NY", "United States"),
    ("NC", "United States"),
    ("ND", "United States"),
    ("OH", "United States"),
    ("OK", "United States"),
    ("OR", "United States"),
    ("PA", "United States"),
    ("RI", "United States"),
    ("SC", "United States"),
    ("SD", "United States"),
    ("TN", "United States"),
    ("TX", "United States"),
    ("UT", "United States"),
    ("VT", "United States"),
    ("VA", "United States"),
    ("WA", "United States"),
    ("WV", "United States"),
    ("WI", "United States"),
    ("WY", "United States"),
    ("DC", "United States"),
    #
    ("Ann Arbor", "United States"),
    ("Oakland", "United States"),
    ("Seattle", "United States"),
    ("Iowa City", "United States"),
    ("Aurora", "United States"),
    ("Indianapolis", "United States"),
    ("La Jolla", "United States"),
    ("Columbus", "United States"),
    ("Kansas City", "United States"),
    ("Corvallis", "United States"),
    ("Minneapolis", "United States"),
    ("Minneapolis MN", "United States"),
    ("Omaha", "United States"),
    ("Dallas", "United States"),
    ("Philadelphia", "United States"),
    ("San Francisco", "United States"),
    ("Boston", "United States"),
    ("Madison", "United States"),
    ("East Lansing", "United States"),
    ("Buffalo", "United States"),
    ("Birmingham", "United States"),
    ("Honolulu", "United States"),
    ("Athens", "United States"),
    ("Sacramento California", "United States"),
    #
    ("Alberta", "Canada"),
    ("British Columbia", "Canada"),
    ("Calgary", "Canada"),
    ("Edmonton", "Canada"),
    ("Manitoba", "Canada"),
    ("New Brunswick", "Canada"),
    ("Newfoundland and Labrador", "Canada"),
    ("Northwest Territories", "Canada"),
    ("Nova Scotia", "Canada"),
    ("Nunavut", "Canada"),
    ("Ontario", "Canada"),
    ("Prince Edward Island", "Canada"),
    ("Quebec", "Canada"),
    ("Saskatchewan", "Canada"),
    ("Toronto", "Canada"),
    ("Yukon", "Canada"),
    #
    ("New South Wales", "Australia"),
    ("Victoria", "Australia"),
    ("Queensland", "Australia"),
    ("Western Australia", "Australia"),
    ("South Australia", "Australia"),
    ("Tasmania", "Australia"),
    ("Australian Capital Territory", "Australia"),
    ("Northern Territory", "Australia"),
    #
    ("Melbourne", "Australia"),
    ("Sydney", "Australia"),
    ("Parkville", "Australia"),
    ("Brisbane", "Australia"),
    ("Adelaide", "Australia"),
    ("Perth", "Australia"),
    ("Canberra", "Australia"),
    ("Bundoora", "Australia"),
    ("Brisbane", "Australia"),
    ("NSW", "Australia"),
    #
    ("Scotland", "United Kingdom"),
    ("Wales", "United Kingdom"),
    #
    ("Peterborough", "United Kingdom"),
    ("Cambridge", "United Kingdom"),
    ("Oxford", "United Kingdom"),
    ("Edinburgh", "United Kingdom"),
    ("Glasgow", "United Kingdom"),
    ("Bristol", "United Kingdom"),
    ("Manchester", "United Kingdom"),
    ("Sheffield", "United Kingdom"),
    #
    ("Søborg", "Denmark"),
]
