from . import (
    cluster_analysis,
    co_word_analysis,
    comparison_between_pairs_of_keywords,
    concordances,
    correspondence_analysis,
    dictionary_based_classification,
    document_clustering,
    lexical_tools,
    modeling_of_emerging_themes,
    multiple_correspondence_analysis,
    sequence_analysis,
    singular_value_decomposition,
    specifity_analysis,
    text_and_discourses,
    thematic_analysis_of_contexts,
    word_assoaciations,
)
