"""Thesaurus module."""

from .apply_thesaurus import ApplyThesaurus
from .create_thesaurus import CreateThesaurus
from .integrity_check import IntegrityCheck
from .reduce_keys import ReduceKeys
from .replace.contains_word_replacer import ContainsWordReplacer
from .replace.ends_with_word_replacer import EndsWithWordReplacer
from .replace.starts_with_word_replacer import StartsWithWordReplacer
from .sort.contains_key_match_sorter import ContainsKeyMatchSorter
from .sort.ends_with_key_match_sorter import EndsWithKeyMatchSorter
from .sort.fuzzy_key_match_sorter import FuzzyKeyMatchSorter
from .sort.key_order_sorter import KeyOrderSorter
from .sort.starts_with_key_match_sorter import StartsWithKeyMatchSorter
from .spell_check import SpellCheck
from .TO_REVIEW._cleanup_thesaurus import CleanupThesaurus
from .TO_REVIEW.common_ending_words_remover import CommonEndingWordsRemover
from .TO_REVIEW.common_starting_words_remover import CommonStartingWordsRemover
from .TO_REVIEW.hyphenated_words_transformer import HyphenatedWordsTransformer
from .TO_REVIEW.parentheses_remover import ParenthesesRemover
from .TO_REVIEW.starting_determiners_remover import StartingDeterminersRemover
from .TO_REVIEW.starting_stopwords_remover import StartingStopwordsRemover
from .translate.american_to_british_translator import AmericanToBritishTranslator
from .translate.british_to_american_translator import BritishToAmericanTranslator
